### PR TITLE
fix(main.ts): Fix properties breaking when using simple quotes

### LINKED ISSUE #2: Single quotes break the summery
# Problem
Unless I misunderstood how to use this plugin and/or Obsidian (very new to this) single quotes break the properties definition when using this plugin.

Obsidian_NNBSr2SALd

The reason is because of how the string is wrapped:
https://github.com/ransurf/live-sync-inline-to-yaml/blob/daa142d49731ad997af0ab2c5255df60a395d1b5/main.ts#L45-L59

The default case is to wrap the text in simple quotes.

# Proposed solution

To prevent formatting issues I'd suggest replacing all instances of `'` with two single quotes `''` (which is how Obsidian seems to escape simple quotes in simple quoted strings)

```ts
wrapInQuotationsIfString(value: string): string {

  // ...

  return `'${value.replaceAll("'", "''")}'`;
}
```

With that small edit, it's all fixed ! 🎉 

Obsidian_QqdvtNfaZh

### PR DESCRIPTION
**Pull request by fabJunior**
Escape simple quotes by replacing them with two simple quotes.
Fixes ransurf/live-sync-inline-to-yaml#2

### CODE REVIEW

**Comment by ransurf** [comment]
sorry was at work when you filed the ticket, I just tried on mine and the solution you suggest throws an error while single quotes don't, weird how our problems are exact opposites.

maybe just not having any quotation wrappings is the best course of action? do you get any errors when you do that?

**Comment by fabJunior** [comment]
What error is thrown? Does it just break your properties?
Can you show me an example?

**Comment by ransurf** [comment]
[image: image.png]
your code implementation is two single quotes '', not a double quote like "
right?

**Comment by fabJunior** [comment]
Correct. Also that image you tried to attach didn't seem to have been uploaded ^^

**Comment by ransurf** [comment]
https://imgur.com/a/JMNW9TI

does this work?

**Comment by fabJunior** [comment]
Yup.
Did you copy paste my solution, cloned my fork, cherry-picked or wrote it by hand? Because I can't seem to reproduce this error. No matter what I write it works fine on my end.

I wonder if you made changes somehow

**Comment by ransurf** [comment]
oh i just manually typed in the two ''

i think the best solution is to get rid of the function as a whole since
now that I think about it it accomplishes nothing 😅

**Comment by fabJunior** [comment]
Obsidian_4bmKL0Z1jS
Wrapping in quotes does help the formatting though!

Can I see the return statement of that function to see what you did? Where you double the single quotes.

Because as far as I'm testing, on Windows with Obsidian 1.4.5 it works flawlessly

**Comment by fabJunior** [comment]
Oh wait, did you actually mean that you typed the two single quotes in your Obsidian note without modifying the code at all? Because that screenshot you showed me wouldn't be a possible case with my modification.

If you were to type for example :
```
\_test: 'This is a test'
```
It would translate to this :
```
---
test: '''This is a test'''
---
```
single quotes are doubled and the whole string is wrapped in single quotes. Which is a valid string

As another exemple :
```
\_test: It's working
```
Would translate to this :
```
---
test: 'It''s working'
---
```

**Comment by ransurf** [comment]
just got back from shower

yes i did manually type it, but just copy pasted your solution and it
breaks with the following line:

https://gyazo.com/cc30901f47bf1a6e5b93230ce0d10854

it broke as soon as I added the ' for don't

**Comment by ransurf** [comment]
also breaks https://gyazo.com/76bd7a25889c110544fcd96f103b447d

**Comment by ransurf** [comment]
this is my fault im not using .replaceAll

**Comment by fabJunior** [comment]
Obsidian_9vF8Q7SlbQ
Obsidian_hydkLIzyz6

I'm pretty confused.

**Comment by fabJunior** [comment]
Ohhh you used "replace" which marvelously replaces the first instance only ^^ JS is awesome ... x)

**Comment by ransurf** [comment]
okay i think it's safe to merge then, thank you for your help ! may i ask
if you code as part of your profession?

**Comment by ransurf** [comment]
i just realized my email responses were being added to github GG

**Comment by fabJunior** [comment]
Yup I do!
I'm a full-stack web developer (mostly frontend though) so I use Javascript on a daily basis in a React environment :)

**Comment by ransurf** [comment]
> Yup I do! I'm a full-stack web developer (mostly frontend though) so I use Javascript on a daily basis in a React environment :)

ooo i respect it 🤝 i also work with js/ts and do front-end with react, please excuse my spaghetti code and functions I was just trying to push something out for my video haha, didn't think anyone would actually take a look and make their own changes :p

**Comment by fabJunior** [comment]
Oh no worries hahaha ^^
I was just trying out that plugin after seeing your video and noticed how it broke when I started using quotes. I made the change locally, then figured it would be nice to share that fix publicly :)

**Comment by ransurf** [comment]
the power of open source B) glad you found the main premise of the plugin
useful ! fix should be merged now :)

**Pull request merged**
